// Customer presentation strings. Keep transport and Maps helpers unchanged.
export const customerCopy = {
  chooseVehicle: 'Тээврийн хэрэгслээ сонго',
  express: 'Шуурхай',
  priceAfterRoute: 'Хаяг сонгоход үнэ гарна',
  priceUpdating: 'Үнэ тооцоолж байна…',
  pickupLabel: 'Авах газар',
  destinationLabel: 'Хүргэх газар',
  destinationPending: 'Хүргэх хаягаа сонгоно уу',
  vehicleDetails: {
    motorcycle: {description: 'Жижиг ачаа · Шуурхай хүргэлт', hint: 'Жижиг хайрцаг, бичиг баримт'},
    amjirgaa: {description: 'Бага, дунд хэмжээний ачаа', hint: 'Хайрцаг, хувцас, жижиг эд зүйлс'},
    porter: {description: 'Том ачаа · Нүүлгэлт', hint: '1 тонн хүртэл'},
  },
  loading: 'Түр хүлээнэ үү…',
  retry: 'Дахин оролдох',
  requestCode: 'Код илгээж байна…',
  verifyCode: 'Код шалгаж байна…',
  phoneHelp: 'Утасны 8 оронтой дугаараа оруулна уу.',
  acceptTerms: 'Үйлчилгээний нөхцөлийг уншиж, зөвшөөрч байна.',
  readTerms: 'Үйлчилгээний нөхцөл унших',
  newWindow: 'Шинэ цонхонд нээгдэнэ',
  termsValidation: 'Үйлчилгээний нөхцөлийг зөвшөөрнө үү.',
  termsRequired: 'Үргэлжлүүлэхийн өмнө үйлчилгээний нөхцөлийг зөвшөөрнө үү.',
  termsAccepted: 'Та үйлчилгээний нөхцөлийг зөвшөөрсөн.',
  codeHelp: 'Баталгаажуулах 2 оронтой кодоо оруулна уу.',
  phoneIntro: 'Таны утасны дугаараар нэвтрэх код авна.',
  error: 'Алдаа гарлаа. Дахин оролдоно уу.',
  searchHelp: 'Хаягаа хайх эсвэл газрын зураг дээр товшино уу.',
  searchShort: 'Хайхын тулд 3-аас доошгүй тэмдэгт оруулна уу.',
  searching: 'Хаяг хайж байна…',
  noResults: 'Хаяг олдсонгүй. Өөр нэрээр хайх эсвэл газрын зураг дээр сонгоно уу.',
  selectedAddress: 'Сонгосон хүргэх хаяг',
  quoteLoading: 'Хаяг, үнийг шинэчилж байна…',
  orderLoading: 'Захиалга илгээж байна…',
  order: 'Захиалах',
  needsAddress: 'Захиалахын тулд хүргэх хаягаа сонгоно уу.',
  needsQuote: 'Үнэ тооцоологдоогүй байна. Дахин тооцоолно уу.',
  retryQuote: 'Үнэ дахин тооцоолох',
  basePrice: 'Эхлэх үнэ',
  payment: 'Төлбөрийн хэлбэр',
  noServices: 'Одоогоор үйлчилгээ байхгүй байна. Түр хүлээгээд дахин оролдоно уу.',
  ratingSaving: 'Үнэлгээг хадгалж байна…',
  ratingSaved: 'Үнэлгээ өгсөнд баярлалаа.',
  cancelling: 'Захиалгыг цуцалж байна…',
  cancelled: 'Захиалга цуцлагдлаа.',
  noDriver: 'Жолооч олдсонгүй. Та дахин захиалах боломжтой.',
  qpayLoading: 'Төлбөрийн мэдээлэл авч байна…',
  reconnecting: 'Холболт тасарлаа. Дахин холбогдож байна…',
} as const;
