'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Route} from 'lucide-react';
import {api,ApiError,phoneFmt} from '@/lib/api';
import {Brand} from './Brand';

export function PhoneLogin({onDone, heading}:{onDone:(user:any)=>void;heading?:string}) {
  const [step,setStep]=useState<'phone'|'code'>('phone'), [phone,setPhone]=useState(''), [code,setCode]=useState('');
  const [busy,setBusy]=useState(false), [error,setError]=useState(''), [seconds,setSeconds]=useState(0);
  useEffect(()=>{if(!seconds)return;const id=setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[seconds]);
  async function request(){setBusy(true);setError('');try{await api('/auth/otp/request',{method:'POST',body:JSON.stringify({phone:'+976'+phone})});setStep('code');setSeconds(60)}catch(e){setError((e as ApiError).message)}finally{setBusy(false)}}
  async function verify(){setBusy(true);setError('');try{const value=await api<{user:any}>('/auth/otp/verify',{method:'POST',body:JSON.stringify({phone:'+976'+phone,code})});onDone(value.user)}catch(e){setError((e as ApiError).message)}finally{setBusy(false)}}
  if(step==='code') return <main className="phone" style={{padding:'20px 24px 32px',display:'flex',flexDirection:'column',gap:22}}><button className="icon-btn" aria-label="Буцах" onClick={()=>setStep('phone')}><ArrowLeft/></button><div><h1 className="display" style={{fontSize:24}}>Кодоо оруулна уу</h1><p className="muted">Туршилтын горим: 0000 кодыг оруулна уу. SMS илгээхгүй.</p></div><input className="field" style={{height:72,textAlign:'center',fontSize:32,fontWeight:700,letterSpacing:18,paddingLeft:18}} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="0000" aria-label="Баталгаажуулах код"/>{error&&<p className="error" role="alert">{error}</p>}<button style={{alignSelf:'flex-start',minHeight:44,border:0,background:'transparent',fontWeight:600,textDecoration:'underline'}} onClick={request} disabled={seconds>0||busy}>{seconds?`Дахин илгээх · ${seconds} сек`:'Код дахин илгээх'}</button><div style={{flex:1}}/><button className="btn btn-primary" disabled={code.length!==4||busy} onClick={verify}>{busy?<span className="spinner"/>:'Баталгаажуулах'}</button></main>;
  return <main className="phone" style={{display:'flex',flexDirection:'column'}}><section style={{height:340,flexShrink:0,position:'relative',overflow:'hidden',padding:'40px 24px 28px',background:'var(--ink)',color:'white',display:'flex',flexDirection:'column',justifyContent:'space-between'}}><Route size={330} color="#f2a516" strokeWidth={.5} style={{position:'absolute',right:-100,top:40,opacity:.35}}/><Brand light/><h1 className="display" style={{fontSize:26,lineHeight:1.25,position:'relative',margin:0}}>{heading||'Ачаагаа хэдхэн товшилтоор тээвэрлүүл'}</h1></section><section style={{padding:'28px 24px 32px',display:'flex',flexDirection:'column',gap:18,flex:1}}><div><h2 style={{fontSize:22,margin:'0 0 6px'}}>Утасны дугаараа оруулна уу</h2><p className="muted" style={{margin:0,lineHeight:1.5}}>Туршилтын горим: SMS илгээхгүй. Дараагийн алхамд 0000 кодыг ашиглана уу.</p></div><div style={{display:'flex',gap:10}}><span style={{width:84,height:56,flexShrink:0,border:'1px solid var(--line-strong)',borderRadius:14,background:'var(--ground)',display:'grid',placeItems:'center',fontWeight:600}}>+976</span><input autoFocus className="field" type="tel" inputMode="numeric" value={phoneFmt(phone)} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,8))} placeholder="8888 8888" aria-label="Утасны дугаар"/></div>{error&&<p className="error" role="alert">{error}</p>}<button className="btn btn-primary" disabled={phone.length!==8||busy} onClick={request}>{busy?<span className="spinner"/>:'Үргэлжлүүлэх'}</button><div style={{flex:1}}/><p className="muted" style={{fontSize:13,textAlign:'center'}}>Үргэлжлүүлснээр та <a href="/terms" style={{color:'var(--ink)',fontWeight:600}}>үйлчилгээний нөхцөл</a>-ийг зөвшөөрнө.</p></section></main>;
}
